# Generated by Django 5.2.5 on 2026-09-16 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_customer_alter_invoice_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='uom',
            field=models.CharField(choices=[('KG', 'KG'), ('Gram', 'Gram'), ('MGram', 'MGram')], default='KG', max_length=10),
        ),
    ]
