# Generated by Django 5.2.5 on 2026-09-30 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waba_id', models.CharField(blank=True, default='', max_length=50)),
                ('phone_number_id', models.CharField(blank=True, default='', max_length=50)),
                ('event_type', models.CharField(blank=True, default='', max_length=50)),
                ('message_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('recipient_id', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('status', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('error_code', models.CharField(blank=True, default='', max_length=50)),
                ('error_message', models.TextField(blank=True, default='')),
                ('event_timestamp', models.DateTimeField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['message_id', 'status'], name='whatsapps_w_message_25dcee_idx'), models.Index(fields=['recipient_id', 'created_at'], name='whatsapps_w_recipie_e93a92_idx')],
            },
        ),
    ]
