# Generated by Django 5.2.5 on 2026-09-30 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapps', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='whatsappwebhookevent',
            options={'ordering': ('-created_at',), 'verbose_name': 'WhatsApp Webhook Event', 'verbose_name_plural': 'WhatsApp Webhook Events'},
        ),
        migrations.RemoveIndex(
            model_name='whatsappwebhookevent',
            name='whatsapps_w_message_25dcee_idx',
        ),
        migrations.RemoveIndex(
            model_name='whatsappwebhookevent',
            name='whatsapps_w_recipie_e93a92_idx',
        ),
        migrations.AddField(
            model_name='whatsappwebhookevent',
            name='direction',
            field=models.CharField(choices=[('incoming', 'Incoming'), ('status', 'Status'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='whatsappwebhookevent',
            name='message_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='whatsappwebhookevent',
            name='message_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='whatsappwebhookevent',
            name='sender_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='whatsappwebhookevent',
            name='event_type',
            field=models.CharField(choices=[('message', 'Incoming Message'), ('status', 'Message Status'), ('other', 'Other')], default='other', max_length=30),
        ),
        migrations.AlterField(
            model_name='whatsappwebhookevent',
            name='phone_number_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='whatsappwebhookevent',
            name='status',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='whatsappwebhookevent',
            name='waba_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
